#ifndef _HEAD_H
#define _HEAD_H
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <dirent.h>
#include <string.h>
#include <fcntl.h>
#include <sys/wait.h>
#include <sys/file.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <pthread.h>
#include <errno.h>
#include <sys/sem.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <poll.h>
#include <sys/epoll.h>
#include <locale.h>
#include <pwd.h>
#include <grp.h>
#include <ctype.h>
#include <sys/ioctl.h>
#include <math.h>
#include <sys/msg.h>
#include "color.h"
#include "msg.h"
#include "common.h"
#include <mysql/mysql.h>
#include "cJSON/cJSON.h"
#include "../server/thread_pool/thread_poll.h"
#include "../server/db_connection_pool/db_connection_pool.h"
#endif
